# Generated by Django 4.1 on 2022-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='category',
            field=models.CharField(choices=[('FPS', 'FPS'), ('MOBA', 'MOBA'), ('ADVANTURE', 'ADVANTURE'), ('COOP', 'COOP'), ('PVP', 'PVP')], default=None, max_length=200),
        ),
    ]
